t4s/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "t4s"
urlpatterns = [
    path('addmodel/', views.addmodel, name='addmodel'),
    path('join/', views.join, name='join'),
    path('success/', views.success, name='success'),
    path('fail/', views.fail, name='fail'),
    path('', views.login, name='login')
    # path('', auth_views.LoginView.as_view(template_name='t4s/login.html'), name='login')
]

type4sec/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('t4s.urls')),
    path('admin/', admin.site.urls),
]

t4s/models.py
from django.db import models

# Create your models here.

t4s/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib import auth
from django.contrib.auth.models import User
from django.db.utils import IntegrityError
import os

from django.utils import asyncio
from tensorflow.python.keras.models import load_model

from t4s.tf.tf import generate_model, to_np, add_to_file

import numpy as np


# login success page
def success(request):
    return HttpResponse("login success!")


def fail(request):
    return HttpResponse("login fail")


# 로그인 페이지
def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(request, username=username, password=password)
        print(user)

        # 아이디 / 비밀번호 일치
        if user is not None:

            keystroke = request.POST.get('keystroke').strip()
            data = to_np(keystroke)

            model = load_model(f"t4s/model/{user}/{user}.h5")
            result = model.predict(data)

            print('========================================================')
            print('data::\t\t', data)
            print('result::\t', result)
            print('========================================================')

            if result:  # result 1 로그인성공
                # 로그인 성공 시 keystroke 추가 수집 => 추가 학습. 정확도 향상
                add_to_file(data, username)

                auth.login(request, user)
                return redirect('t4s:success')

            else:  # result가 0 로그인 실패
                return redirect('t4s:fail')

        # 아이디 / 비밀번호 불일치
        else:
            return render(request, 't4s/login.html', {'error': '아이디, 비밀번호 확인'})

    else:
        return render(request, 't4s/login.html')


# 회원가입 페이지
def join(request):
    if request.method == "POST":
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        password3 = request.POST['password3']
        password4 = request.POST['password4']
        password5 = request.POST['password5']
        keystroke1 = request.POST['keystroke1']
        keystroke2 = request.POST['keystroke2']
        keystroke3 = request.POST['keystroke3']
        keystroke4 = request.POST['keystroke4']
        keystroke5 = request.POST['keystroke5']

        if password1 == password2 == password3 == password4 == password5:

            keystroke1 = to_np(keystroke1)
            keystroke2 = to_np(keystroke2)
            keystroke3 = to_np(keystroke3)
            keystroke4 = to_np(keystroke4)
            keystroke5 = to_np(keystroke5)

            # keystroke의 길이가 모두 같은지 검사
            if keystroke1.shape[1] == keystroke2.shape[1] == keystroke3.shape[1] == keystroke4.shape[1] == keystroke5.shape[1]:
                keystroke = np.append(keystroke1, keystroke2, axis=0)
                keystroke = np.append(keystroke, keystroke3, axis=0)
                keystroke = np.append(keystroke, keystroke4, axis=0)
                keystroke = np.append(keystroke, keystroke5, axis=0)
                print(keystroke)

            else:
                return render(request, 't4s/join.html', {'error': '오타 없이 한번에'})

            # 회원가입 시도
            try:
                User.objects.create_user(username=username, password=password1)
            except IntegrityError:  # ID 중복
                return render(request, 't4s/join.html', {'error': 'ID 중복'})

            # 유저별 h5 파일과 npy 파일을 저장할 폴더 생성.
            if os.path.isdir('t4s/model/' + username) is False:
                os.makedirs('t4s/model/' + username)

            # 입력 받은 keystroke 데이터 numpy 파일로 저장
            print(':::::::::', keystroke)
            add_to_file(keystroke, username)
            # h5 파일 생성
            generate_model(keystroke).save(f"t4s/model/{username}/{username}.h5")

            return render(request, 't4s/join.html', {'error': '회원가입 성공'})

        # 비밀번호 오타
        else:
            return render(request, 't4s/join.html', {'error': '비밀번호 확인'})


    else:
        return render(request, 't4s/join.html')


# 모델추가
def addmodel(request):
    if request.method == "POST":

        keystroke = request.POST.get('keystroke')
        data = to_np(keystroke)

        try:
            x_train = np.load('t4s/model/x_train.npy')
        except FileNotFoundError:
            x_train = data

        x_train = np.append(x_train, data, axis=0)
        np.save('t4s/model/x_train.npy', x_train)

        return render(request, 't4s/addmodel.html', {'count': x_train.shape})

    else:
        return render(request, 't4s/addmodel.html')

templates/t4s/join.html
{% load static%}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
<meta name="generator" content="Hugo 0.84.0">


<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

<link href="{% static 'signin.css' %}" rel="stylesheet">

{% block content %}

<body class = "text-center">
    <div class="form-signin">
        <h1 class="text-center">회원가입</h1>
        <hr>
        <form class="inputs" method="post" action="{% url 't4s:join' %}" id="form">
            {% csrf_token %}
            <div>
                <label>사용자 ID</label>
                <input class="form-control" type="text" name="username" id="username" placeholder="User ID">
            </div>
            <br>
            <div>
                <label>비밀번호</label>
                <input class="form-control"type="password" name="password1" id="password1" placeholder="Password 1">
            </div>
            <br>
            <div>
                <input class="form-control" type="password" name="password2" id="password2" placeholder="Password 2">
            </div>
            <br>
            <div>
                <input class="form-control" type="password" name="password3" id="password3" placeholder="Password 3">
            </div>
            <br>
            <div>
                <input class="form-control" type="password" name="password4" id="password4" placeholder="Password 4">
            </div>
            <br>
            <div>
                <input class="form-control" type="password" name="password5" id="password5" placeholder="Password 5">
            </div>
            <br>
            <script>
                const password1 = document.getElementById('password1');
                const password2 = document.getElementById('password2');
                const password3 = document.getElementById('password3');
                const password4 = document.getElementById('password4');
                const password5 = document.getElementById('password5');

                let last;
                let keystroke1 = []; //키 간격 데이터 배열
                let keystroke2 = [];
                let keystroke3 = [];
                let keystroke4 = [];
                let keystroke5 = [];

                let i = -1; //0으로 하면 누르는 순간 i가 1증가. 배열의 첫번째 값이 NaN이 됨

                password1.addEventListener("input", () => {
                    let n = new Date();
                    keystroke1[i] = last-n;
                    i++;
                    last = n;
                });

                password2.addEventListener("input", () => {
                    let n = new Date();
                    keystroke2[i] = last-n;
                    i++;
                    last = n;
                });

                password3.addEventListener("input", () => {
                    let n = new Date();
                    keystroke3[i] = last-n;
                    i++;
                    last = n;
                });

                password4.addEventListener("input", () => {
                    let n = new Date();
                    keystroke4[i] = last-n;
                    i++;
                    last = n;
                });

                password5.addEventListener("input", () => {
                    let n = new Date();
                    keystroke5[i] = last-n;
                    i++;
                    last = n;
                });


                //password 의 입력이 끝나 blur 되었을 때
                password1.addEventListener("blur", initVar);
                password2.addEventListener("blur", initVar);
                password3.addEventListener("blur", initVar);
                password4.addEventListener("blur", initVar);
                password5.addEventListener("blur", initVar);



                // 전송 버튼 눌렀을 때 실행될 함수
                function sendData() {
                    document.getElementById("keystroke1").value = keystroke1;
                    document.getElementById("keystroke2").value = keystroke2;
                    document.getElementById("keystroke3").value = keystroke3;
                    document.getElementById("keystroke4").value = keystroke4;
                    document.getElementById("keystroke5").value = keystroke5;
                    document.getElementById("form").submit();
                }

                // 각 필드의 입력이 끝났을 때 필요한 변수 초기화
                function initVar() {
                    last = null;
                    i = -1;
                }

            </script>
            <input type="hidden" name="keystroke1" id="keystroke1">
            <input type="hidden" name="keystroke2" id="keystroke2">
            <input type="hidden" name="keystroke3" id="keystroke3">
            <input type="hidden" name="keystroke4" id="keystroke4">
            <input type="hidden" name="keystroke5" id="keystroke5">
            <button class="btn btn-primary btn-block mb-4" type="button" onclick="sendData()">회원가입</button>
        </form>
        <p>로그인 페이지로  <a href="/">  돌아가기</a></p>
            <h1>{{ error }}</h1>
    </div>



</body>
{% endblock %}

templates/t4s/login.html
{% load static%}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
<meta name="generator" content="Hugo 0.84.0">


<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

<link href="{% static 'signin.css' %}" rel="stylesheet">

<style>
</style>


{% block content %}
<body class = "text-center">

        <main class="form-signin" text-align="center">
            <h1 class="mb-4">로그인</h1>
            <form method="post" action="{% url 't4s:login' %}" id="form">
                {% csrf_token %}
                <div>
                    <input class="form-control" type="text" name="username" id="username" placeholder="User ID">
                </div>
                <br>
                <div>
                    <input class="form-control" type="password" name="password" id="password" placeholder="Password">
                </div>
                <hr>
                간격: <div class="form-outline mb-4" id="output" style="text-align:left"></div>
                <script>
                    const output = document.getElementById('output');
                    const password = document.getElementById('password');
                    let last;
                    let keystroke = []; //키 간격 데이터 배열
                    let i = -1; //0으로 하면 누르는 순간 i가 1증가. 배열의 첫번째 값이 NaN이 됨

                    password.addEventListener("keydown", (e) => {
                        //엔터키 입력 시 바로 데이터 전송. 마지막 글자와 엔터 사이 간격은 전송하지 않기 위해 return
                        if (e.key == 'Enter'){
                            sendData();
                            return;
                        }
                        let n = new Date();
                        output.textContent = (last-n).toString() + 'ms';
                        keystroke[i] = last-n;
                        i++;
                        last = n;
                    });

                    //password blur 되는 순간 간격 배열 보여줌. 테스트용.
                    password.addEventListener("blur", () => {
                        output.textContent = keystroke.toString();
                    })

                    function sendData() {
                        document.getElementById("keystroke").value = keystroke;
                        document.getElementById("form").submit();
                    }

                </script>
                <input type="hidden" name="keystroke" id="keystroke">
                <button class="btn btn-primary btn-block mb-4" type="button" onclick="sendData()">로그인</button>
            </form>
           
            <p>아직 회원이 아니신가요? <a href="/join">  회원가입</a></p>

            <hr>
            <p><b>{{ error }}</b></p>   
        </main>
        <hr>
     
    
</body>
{% endblock %}